dist: trusty
language: python
python: 3.6

env:
    - TOXENV=lint
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=py36


before_install:
    # Workaround for https://github.com/travis-ci/travis-ci/issues/8363
    - pyenv global system 3.5

install:
    - pip install -U tox
    - pip install -U coveralls

script:
    - tox

after_success:
    coveralls
