language:
    python

python:
    - "2.7"

env:
    - TOXENV=lint
    - TOXENV=py27

before_install:
    - echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list
    - sudo apt-get update -qq
    - sudo apt-get install gnupg2

install:
    - pip install tox
    - pip install coveralls

script:
    - gpg2 --version
    - tox

after_success:
    coveralls
